"""
Standalone SHAP Viewer - View SHAP plots in browser
Run: streamlit run shap_viewer.py
"""

import streamlit as st
import sys
from pathlib import Path

# Add project root
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))

from PIL import Image

st.set_page_config(
    page_title="SHAP Fraud Explanations",
    page_icon="🔬",
    layout="wide"
)

st.title("🔬 SHAP Fraud Explanations Viewer")
st.markdown("View SHAP plots generated by the fraud detection system")
st.markdown("---")

# Check if plots exist
plot_dir = Path("results/feature_importance")
shap_dir = Path("results/shap_plots")

if not plot_dir.exists() and not shap_dir.exists():
    st.error("❌ No plots found!")
    st.markdown("""
    ### Generate plots first:
    
    Run one of these commands:
    ```bash
    python feature_importance_viz.py
    # OR
    python quick_shap_demo.py
    ```
    
    Then refresh this page.
    """)
else:
    # Show feature importance plots
    if plot_dir.exists():
        st.header("📊 Feature Importance Analysis")
        
        plots = list(plot_dir.glob("*.png"))
        
        if plots:
            for plot_path in sorted(plots):
                st.subheader(f"📈 {plot_path.stem.replace('_', ' ').title()}")
                
                try:
                    image = Image.open(plot_path)
                    st.image(image, use_column_width=True)
                except Exception as e:
                    st.error(f"Could not load {plot_path.name}: {e}")
                
                st.markdown("---")
        else:
            st.warning("No plots found in results/feature_importance/")
    
    # Show SHAP plots
    if shap_dir.exists():
        st.header("🔬 SHAP Explanations")
        
        plots = list(shap_dir.glob("*.png"))
        
        if plots:
            for plot_path in sorted(plots):
                st.subheader(f"🎯 {plot_path.stem.replace('_', ' ').title()}")
                
                # Add description based on plot type
                if 'waterfall' in plot_path.name:
                    st.markdown("""
                    **Waterfall Plot**: Shows how each feature contributes to the fraud score
                    - Red bars push the score higher (more fraudulent)
                    - Blue bars push the score lower (less fraudulent)
                    """)
                elif 'force' in plot_path.name:
                    st.markdown("""
                    **Force Plot**: Visualizes features pushing the prediction
                    - Red = increasing fraud score
                    - Blue = decreasing fraud score
                    """)
                elif 'summary' in plot_path.name:
                    st.markdown("""
                    **Summary Plot**: Feature importance across all claims
                    - Higher position = more important
                    - Color shows feature value (red=high, blue=low)
                    """)
                
                try:
                    image = Image.open(plot_path)
                    st.image(image, use_column_width=True)
                except Exception as e:
                    st.error(f"Could not load {plot_path.name}: {e}")
                
                st.markdown("---")
        else:
            st.warning("No SHAP plots found in results/shap_plots/")
    
    # Download section
    st.header("💾 Download Plots")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.markdown("### Feature Importance Plots")
        if plot_dir.exists():
            for plot_path in sorted(plot_dir.glob("*.png")):
                with open(plot_path, "rb") as f:
                    st.download_button(
                        label=f"📥 {plot_path.name}",
                        data=f.read(),
                        file_name=plot_path.name,
                        mime="image/png"
                    )
    
    with col2:
        st.markdown("### SHAP Plots")
        if shap_dir.exists():
            for plot_path in sorted(shap_dir.glob("*.png")):
                with open(plot_path, "rb") as f:
                    st.download_button(
                        label=f"📥 {plot_path.name}",
                        data=f.read(),
                        file_name=plot_path.name,
                        mime="image/png"
                    )

# Instructions
st.sidebar.markdown("""
## 📖 Instructions

1. Generate plots first:
   ```bash
   python feature_importance_viz.py
   ```

2. Refresh this page

3. View and download plots

### Plot Types:

**Feature Importance**:
- Overall importance
- Top claim anomalies  
- Fraud distribution
- Heatmap

**SHAP** (if available):
- Waterfall plots
- Force plots
- Summary plots
- Bar plots
""")
